### ISSUE TITLE
Repository is empty

### ISSUE THREAD

**Issue by wylited** [PurpleSe4shell/PurpleSe4shell#1]
big issue, how is it hosting a site if the repository is empty lol.

**Comment by Mini-Touch** [comment]
true

**Comment by WMFong0** [comment]
Very True

**Comment by ryanlaw119** [comment]
😭😭

**Comment by PurpleSe4shell** [comment]
because when you have Github Pro, you can have private repo and use GitHub pages 😉
Sign up here!: https://education.github.com/pack

**Comment by wylited** [comment]
got it!
